# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 508304416213661c3f47d12238bc27cc0fba088b39cc834ed5ccaa05da6b1c9f42f6d4421a7f53d554a91238d106982b949e57b89be1d900a297b824de6a0c00

test:
  secret_key_base: 0c28f5cc7b8cea19466589510910326d171223172422b34ab849942860614b2da9fdefb27eb460f4324b75bdf106cae10b44a5478ede2dacad45f0afc693f84a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
